### ISSUE TITLE
The name "QuantLib" is already in use

### ISSUE THREAD

**Issue by lballabio** [MikaelUmaN/quantlib#1]
Hello,
    unfortunately, the name "quantlib" has been used for some 15 years by another project--see <http://quantlib.org>.  This makes your project practically impossible to find, as Google will return dozens of hits for the other one before yours...

**Comment by MikaelUmaN** [comment]
Thank you for your comment and interest. Of course I am aware of that library. But this is just some hobby code I do on my free time. I am completely fine with the not being shown on Google or other sites.

Using com.rainysoft as a differentiator should suffice. If you have further concerns please tell me.

**Comment by lballabio** [comment]
Ok then. Good luck with your effort!
